# Generated by Django 3.0.8 on 2020-09-09 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_banner', models.ImageField(upload_to='static/production/about_us_banner')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 929941))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 929941))),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', models.ImageField(upload_to='static/production/category')),
                ('category_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 929941))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 929941))),
            ],
        ),
        migrations.CreateModel(
            name='home_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='static/production/home_banner')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 929941))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 929941))),
            ],
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('item_name', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 929941))),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='static/production/product')),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 925941))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 925941))),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.ImageField(upload_to='static/production/team')),
                ('member_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 929941))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 43, 32, 929941))),
            ],
        ),
    ]
