# Generated by Django 3.0.8 on 2020-09-10 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvkadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us_banner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='about_us_banner',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 15, 4, 55, 386595)),
        ),
    ]
