# Generated by Django 3.0.8 on 2020-09-12 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvkadmin', '0002_auto_20200910_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about_us_banner',
        ),
        migrations.AddField(
            model_name='home_banner',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='production/category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 51, 15, 189786)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 51, 15, 189786)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='banner_image',
            field=models.ImageField(upload_to='production/home_banner'),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 51, 15, 193775)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 51, 15, 193775)),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 51, 15, 193775)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 51, 15, 189786)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='production/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 51, 15, 189786)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 51, 15, 193775)),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_image',
            field=models.ImageField(upload_to='production/team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 51, 15, 193775)),
        ),
    ]
