# Generated by Django 3.0.8 on 2020-09-13 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvkadmin', '0004_auto_20200912_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 515329))),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 514331)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 514331)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 515329)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 515329)),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 515329)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 513334)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 514331)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 514331)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 15, 11, 40, 514331)),
        ),
    ]
