# Generated by Django 3.0.8 on 2020-09-28 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvkadmin', '0005_auto_20200913_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='production/about_us')),
                ('category', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 873005))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 873005))),
            ],
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='item_name',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 873965)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 870972)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 870972)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 871970)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 871970)),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 873965)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 873005)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 870014)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 870014)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 870972)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 35, 24, 870972)),
        ),
    ]
