# Generated by Django 3.0.8 on 2020-10-02 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvkadmin', '0011_auto_20200928_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_image_1',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, upload_to='production/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(blank=True, upload_to='production/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_4',
            field=models.ImageField(blank=True, upload_to='production/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_5',
            field=models.ImageField(blank=True, upload_to='production/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_6',
            field=models.ImageField(blank=True, upload_to='production/product'),
        ),
        migrations.AlterField(
            model_name='about_banner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 115832)),
        ),
        migrations.AlterField(
            model_name='about_banner',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 115832)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 113838)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 113838)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 116829)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 116829)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 114835)),
        ),
        migrations.AlterField(
            model_name='home_banner',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 114835)),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 114835)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 115832)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 112841)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 112841)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 113838)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 9, 12, 19, 113838)),
        ),
    ]
