# Generated by Django 3.0.8 on 2020-09-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
