# Generated by Django 3.0.8 on 2020-09-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvk', '0002_auto_20200903_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to='static/artwork '),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image1',
            field=models.ImageField(upload_to='static/poster'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image2',
            field=models.ImageField(upload_to='static/poster'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image3',
            field=models.ImageField(upload_to='static/poster'),
        ),
    ]
