# Generated by Django 3.0.8 on 2020-09-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvk', '0003_auto_20200909_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='artwork',
        ),
        migrations.DeleteModel(
            name='enquiry',
        ),
        migrations.DeleteModel(
            name='poster',
        ),
    ]
